java:
  # Don't modify below here
  image: ${IMAGE_NAME}
  ingressHost: ${SERVICE_FQDN}
  environment:
    DRAFT_STORE_DB_CONN_OPTIONS: ?sslmode=require
    DRAFT_STORE_DB_HOST: rpe-draft-store-aat.postgres.database.azure.com
    DRAFT_STORE_DB_NAME: draftstore
    DRAFT_STORE_DB_USER_NAME: draftstore@rpe-draft-store-aat
    RUN_DB_MIGRATION_ON_STARTUP: 'false'
    IDAM_URL: https://idam-api.aat.platform.hmcts.net
    S2S_URL: http://rpe-service-auth-provider-java
  keyVaults:
    "draft-store":
      resourceGroup: draft-store-service
      secrets:
        - service-POSTGRES-PASS
