idam_api_url                = "https://idam-api.ithc.platform.hmcts.net"
use_idam_testing_support    = "false"
idam_redirect_uri_for_tests = "https://cmc-citizen-frontend-ithc.service.core-compute-ithc.internal/receiver"
pgsql_create_mode           = "Update"
pgsql_version               = "15"
